#define INTERNAL_ERROR -1
#define UNRECOGNIZED_NODE_TYPE -2
#define TYPE_MISMATCH -3

#define UNDEFINED_VARIABLE -4
#define ARGUMENT_ERROR -5

#define NO_METHOD_ERROR -6
#define WRONG_NUMBER_ARGUMENTS -7
